### ISSUE TITLE
Create provenance story backed up by curl requests

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/prov-service#2] opened 2019-04-16 15:08 UTC
The idea is to have a list of `curl` requests that we can execute to build a provenance graph before actually implementing them into the portal and tools (FE-lite).

**Comment by ychae** [comment] 2019-06-13 19:47
Is this a duplicate of #7? Or something else entirely?

**Comment by jaeddy** [comment] 2019-06-28 19:03
Not quite. Now that we have the mock provenance records, and once we implement a few more of the queries in #13, we can step through a series of example queries formatted as `curl` requests (to be as generic as possible). @tschaffter can then implement these requests in the portal.

**Comment by jaeddy** [comment] 2019-07-24 07:17
No longer need `curl` examples; core provenance service requests implemented in portal back end.

**Closed by jaeddy** 2019-07-24 07:17 UTC
Labels: Documentation, Provenance
